"""
typing stub file
"""

from opcua.ua.uaerrors import UaStatusCodeError as UaStatusCodeError

class Bad(UaStatusCodeError):
    code: int = ...

class BadUnexpectedError(UaStatusCodeError):
    code: int = ...

class BadInternalError(UaStatusCodeError):
    code: int = ...

class BadOutOfMemory(UaStatusCodeError):
    code: int = ...

class BadResourceUnavailable(UaStatusCodeError):
    code: int = ...

class BadCommunicationError(UaStatusCodeError):
    code: int = ...

class BadEncodingError(UaStatusCodeError):
    code: int = ...

class BadDecodingError(UaStatusCodeError):
    code: int = ...

class BadEncodingLimitsExceeded(UaStatusCodeError):
    code: int = ...

class BadRequestTooLarge(UaStatusCodeError):
    code: int = ...

class BadResponseTooLarge(UaStatusCodeError):
    code: int = ...

class BadUnknownResponse(UaStatusCodeError):
    code: int = ...

class BadTimeout(UaStatusCodeError):
    code: int = ...

class BadServiceUnsupported(UaStatusCodeError):
    code: int = ...

class BadShutdown(UaStatusCodeError):
    code: int = ...

class BadServerNotConnected(UaStatusCodeError):
    code: int = ...

class BadServerHalted(UaStatusCodeError):
    code: int = ...

class BadNothingToDo(UaStatusCodeError):
    code: int = ...

class BadTooManyOperations(UaStatusCodeError):
    code: int = ...

class BadTooManyMonitoredItems(UaStatusCodeError):
    code: int = ...

class BadDataTypeIdUnknown(UaStatusCodeError):
    code: int = ...

class BadCertificateInvalid(UaStatusCodeError):
    code: int = ...

class BadSecurityChecksFailed(UaStatusCodeError):
    code: int = ...

class BadCertificateTimeInvalid(UaStatusCodeError):
    code: int = ...

class BadCertificateIssuerTimeInvalid(UaStatusCodeError):
    code: int = ...

class BadCertificateHostNameInvalid(UaStatusCodeError):
    code: int = ...

class BadCertificateUriInvalid(UaStatusCodeError):
    code: int = ...

class BadCertificateUseNotAllowed(UaStatusCodeError):
    code: int = ...

class BadCertificateIssuerUseNotAllowed(UaStatusCodeError):
    code: int = ...

class BadCertificateUntrusted(UaStatusCodeError):
    code: int = ...

class BadCertificateRevocationUnknown(UaStatusCodeError):
    code: int = ...

class BadCertificateIssuerRevocationUnknown(UaStatusCodeError):
    code: int = ...

class BadCertificateRevoked(UaStatusCodeError):
    code: int = ...

class BadCertificateIssuerRevoked(UaStatusCodeError):
    code: int = ...

class BadCertificateChainIncomplete(UaStatusCodeError):
    code: int = ...

class BadUserAccessDenied(UaStatusCodeError):
    code: int = ...

class BadIdentityTokenInvalid(UaStatusCodeError):
    code: int = ...

class BadIdentityTokenRejected(UaStatusCodeError):
    code: int = ...

class BadSecureChannelIdInvalid(UaStatusCodeError):
    code: int = ...

class BadInvalidTimestamp(UaStatusCodeError):
    code: int = ...

class BadNonceInvalid(UaStatusCodeError):
    code: int = ...

class BadSessionIdInvalid(UaStatusCodeError):
    code: int = ...

class BadSessionClosed(UaStatusCodeError):
    code: int = ...

class BadSessionNotActivated(UaStatusCodeError):
    code: int = ...

class BadSubscriptionIdInvalid(UaStatusCodeError):
    code: int = ...

class BadRequestHeaderInvalid(UaStatusCodeError):
    code: int = ...

class BadTimestampsToReturnInvalid(UaStatusCodeError):
    code: int = ...

class BadRequestCancelledByClient(UaStatusCodeError):
    code: int = ...

class BadTooManyArguments(UaStatusCodeError):
    code: int = ...

class BadNoCommunication(UaStatusCodeError):
    code: int = ...

class BadWaitingForInitialData(UaStatusCodeError):
    code: int = ...

class BadNodeIdInvalid(UaStatusCodeError):
    code: int = ...

class BadNodeIdUnknown(UaStatusCodeError):
    code: int = ...

class BadAttributeIdInvalid(UaStatusCodeError):
    code: int = ...

class BadIndexRangeInvalid(UaStatusCodeError):
    code: int = ...

class BadIndexRangeNoData(UaStatusCodeError):
    code: int = ...

class BadDataEncodingInvalid(UaStatusCodeError):
    code: int = ...

class BadDataEncodingUnsupported(UaStatusCodeError):
    code: int = ...

class BadNotReadable(UaStatusCodeError):
    code: int = ...

class BadNotWritable(UaStatusCodeError):
    code: int = ...

class BadOutOfRange(UaStatusCodeError):
    code: int = ...

class BadNotSupported(UaStatusCodeError):
    code: int = ...

class BadNotFound(UaStatusCodeError):
    code: int = ...

class BadObjectDeleted(UaStatusCodeError):
    code: int = ...

class BadNotImplemented(UaStatusCodeError):
    code: int = ...

class BadMonitoringModeInvalid(UaStatusCodeError):
    code: int = ...

class BadMonitoredItemIdInvalid(UaStatusCodeError):
    code: int = ...

class BadMonitoredItemFilterInvalid(UaStatusCodeError):
    code: int = ...

class BadMonitoredItemFilterUnsupported(UaStatusCodeError):
    code: int = ...

class BadFilterNotAllowed(UaStatusCodeError):
    code: int = ...

class BadStructureMissing(UaStatusCodeError):
    code: int = ...

class BadEventFilterInvalid(UaStatusCodeError):
    code: int = ...

class BadContentFilterInvalid(UaStatusCodeError):
    code: int = ...

class BadFilterOperatorInvalid(UaStatusCodeError):
    code: int = ...

class BadFilterOperatorUnsupported(UaStatusCodeError):
    code: int = ...

class BadFilterOperandCountMismatch(UaStatusCodeError):
    code: int = ...

class BadFilterOperandInvalid(UaStatusCodeError):
    code: int = ...

class BadFilterElementInvalid(UaStatusCodeError):
    code: int = ...

class BadFilterLiteralInvalid(UaStatusCodeError):
    code: int = ...

class BadContinuationPointInvalid(UaStatusCodeError):
    code: int = ...

class BadNoContinuationPoints(UaStatusCodeError):
    code: int = ...

class BadReferenceTypeIdInvalid(UaStatusCodeError):
    code: int = ...

class BadBrowseDirectionInvalid(UaStatusCodeError):
    code: int = ...

class BadNodeNotInView(UaStatusCodeError):
    code: int = ...

class BadServerUriInvalid(UaStatusCodeError):
    code: int = ...

class BadServerNameMissing(UaStatusCodeError):
    code: int = ...

class BadDiscoveryUrlMissing(UaStatusCodeError):
    code: int = ...

class BadSempahoreFileMissing(UaStatusCodeError):
    code: int = ...

class BadRequestTypeInvalid(UaStatusCodeError):
    code: int = ...

class BadSecurityModeRejected(UaStatusCodeError):
    code: int = ...

class BadSecurityPolicyRejected(UaStatusCodeError):
    code: int = ...

class BadTooManySessions(UaStatusCodeError):
    code: int = ...

class BadUserSignatureInvalid(UaStatusCodeError):
    code: int = ...

class BadApplicationSignatureInvalid(UaStatusCodeError):
    code: int = ...

class BadNoValidCertificates(UaStatusCodeError):
    code: int = ...

class BadIdentityChangeNotSupported(UaStatusCodeError):
    code: int = ...

class BadRequestCancelledByRequest(UaStatusCodeError):
    code: int = ...

class BadParentNodeIdInvalid(UaStatusCodeError):
    code: int = ...

class BadReferenceNotAllowed(UaStatusCodeError):
    code: int = ...

class BadNodeIdRejected(UaStatusCodeError):
    code: int = ...

class BadNodeIdExists(UaStatusCodeError):
    code: int = ...

class BadNodeClassInvalid(UaStatusCodeError):
    code: int = ...

class BadBrowseNameInvalid(UaStatusCodeError):
    code: int = ...

class BadBrowseNameDuplicated(UaStatusCodeError):
    code: int = ...

class BadNodeAttributesInvalid(UaStatusCodeError):
    code: int = ...

class BadTypeDefinitionInvalid(UaStatusCodeError):
    code: int = ...

class BadSourceNodeIdInvalid(UaStatusCodeError):
    code: int = ...

class BadTargetNodeIdInvalid(UaStatusCodeError):
    code: int = ...

class BadDuplicateReferenceNotAllowed(UaStatusCodeError):
    code: int = ...

class BadInvalidSelfReference(UaStatusCodeError):
    code: int = ...

class BadReferenceLocalOnly(UaStatusCodeError):
    code: int = ...

class BadNoDeleteRights(UaStatusCodeError):
    code: int = ...

class BadServerIndexInvalid(UaStatusCodeError):
    code: int = ...

class BadViewIdUnknown(UaStatusCodeError):
    code: int = ...

class BadViewTimestampInvalid(UaStatusCodeError):
    code: int = ...

class BadViewParameterMismatch(UaStatusCodeError):
    code: int = ...

class BadViewVersionInvalid(UaStatusCodeError):
    code: int = ...

class BadNotTypeDefinition(UaStatusCodeError):
    code: int = ...

class BadTooManyMatches(UaStatusCodeError):
    code: int = ...

class BadQueryTooComplex(UaStatusCodeError):
    code: int = ...

class BadNoMatch(UaStatusCodeError):
    code: int = ...

class BadMaxAgeInvalid(UaStatusCodeError):
    code: int = ...

class BadSecurityModeInsufficient(UaStatusCodeError):
    code: int = ...

class BadHistoryOperationInvalid(UaStatusCodeError):
    code: int = ...

class BadHistoryOperationUnsupported(UaStatusCodeError):
    code: int = ...

class BadInvalidTimestampArgument(UaStatusCodeError):
    code: int = ...

class BadWriteNotSupported(UaStatusCodeError):
    code: int = ...

class BadTypeMismatch(UaStatusCodeError):
    code: int = ...

class BadMethodInvalid(UaStatusCodeError):
    code: int = ...

class BadArgumentsMissing(UaStatusCodeError):
    code: int = ...

class BadTooManySubscriptions(UaStatusCodeError):
    code: int = ...

class BadTooManyPublishRequests(UaStatusCodeError):
    code: int = ...

class BadNoSubscription(UaStatusCodeError):
    code: int = ...

class BadSequenceNumberUnknown(UaStatusCodeError):
    code: int = ...

class BadMessageNotAvailable(UaStatusCodeError):
    code: int = ...

class BadInsufficientClientProfile(UaStatusCodeError):
    code: int = ...

class BadStateNotActive(UaStatusCodeError):
    code: int = ...

class BadTcpServerTooBusy(UaStatusCodeError):
    code: int = ...

class BadTcpMessageTypeInvalid(UaStatusCodeError):
    code: int = ...

class BadTcpSecureChannelUnknown(UaStatusCodeError):
    code: int = ...

class BadTcpMessageTooLarge(UaStatusCodeError):
    code: int = ...

class BadTcpNotEnoughResources(UaStatusCodeError):
    code: int = ...

class BadTcpInternalError(UaStatusCodeError):
    code: int = ...

class BadTcpEndpointUrlInvalid(UaStatusCodeError):
    code: int = ...

class BadRequestInterrupted(UaStatusCodeError):
    code: int = ...

class BadRequestTimeout(UaStatusCodeError):
    code: int = ...

class BadSecureChannelClosed(UaStatusCodeError):
    code: int = ...

class BadSecureChannelTokenUnknown(UaStatusCodeError):
    code: int = ...

class BadSequenceNumberInvalid(UaStatusCodeError):
    code: int = ...

class BadProtocolVersionUnsupported(UaStatusCodeError):
    code: int = ...

class BadConfigurationError(UaStatusCodeError):
    code: int = ...

class BadNotConnected(UaStatusCodeError):
    code: int = ...

class BadDeviceFailure(UaStatusCodeError):
    code: int = ...

class BadSensorFailure(UaStatusCodeError):
    code: int = ...

class BadOutOfService(UaStatusCodeError):
    code: int = ...

class BadDeadbandFilterInvalid(UaStatusCodeError):
    code: int = ...

class BadRefreshInProgress(UaStatusCodeError):
    code: int = ...

class BadConditionAlreadyDisabled(UaStatusCodeError):
    code: int = ...

class BadConditionAlreadyEnabled(UaStatusCodeError):
    code: int = ...

class BadConditionDisabled(UaStatusCodeError):
    code: int = ...

class BadEventIdUnknown(UaStatusCodeError):
    code: int = ...

class BadEventNotAcknowledgeable(UaStatusCodeError):
    code: int = ...

class BadDialogNotActive(UaStatusCodeError):
    code: int = ...

class BadDialogResponseInvalid(UaStatusCodeError):
    code: int = ...

class BadConditionBranchAlreadyAcked(UaStatusCodeError):
    code: int = ...

class BadConditionBranchAlreadyConfirmed(UaStatusCodeError):
    code: int = ...

class BadConditionAlreadyShelved(UaStatusCodeError):
    code: int = ...

class BadConditionNotShelved(UaStatusCodeError):
    code: int = ...

class BadShelvingTimeOutOfRange(UaStatusCodeError):
    code: int = ...

class BadNoData(UaStatusCodeError):
    code: int = ...

class BadBoundNotFound(UaStatusCodeError):
    code: int = ...

class BadBoundNotSupported(UaStatusCodeError):
    code: int = ...

class BadDataLost(UaStatusCodeError):
    code: int = ...

class BadDataUnavailable(UaStatusCodeError):
    code: int = ...

class BadEntryExists(UaStatusCodeError):
    code: int = ...

class BadNoEntryExists(UaStatusCodeError):
    code: int = ...

class BadTimestampNotSupported(UaStatusCodeError):
    code: int = ...

class BadAggregateListMismatch(UaStatusCodeError):
    code: int = ...

class BadAggregateNotSupported(UaStatusCodeError):
    code: int = ...

class BadAggregateInvalidInputs(UaStatusCodeError):
    code: int = ...

class BadAggregateConfigurationRejected(UaStatusCodeError):
    code: int = ...

class BadRequestNotAllowed(UaStatusCodeError):
    code: int = ...

class BadDominantValueChanged(UaStatusCodeError):
    code: int = ...

class BadDependentValueChanged(UaStatusCodeError):
    code: int = ...

class BadInvalidArgument(UaStatusCodeError):
    code: int = ...

class BadConnectionRejected(UaStatusCodeError):
    code: int = ...

class BadDisconnect(UaStatusCodeError):
    code: int = ...

class BadConnectionClosed(UaStatusCodeError):
    code: int = ...

class BadInvalidState(UaStatusCodeError):
    code: int = ...

class BadEndOfStream(UaStatusCodeError):
    code: int = ...

class BadNoDataAvailable(UaStatusCodeError):
    code: int = ...

class BadWaitingForResponse(UaStatusCodeError):
    code: int = ...

class BadOperationAbandoned(UaStatusCodeError):
    code: int = ...

class BadExpectedStreamToBlock(UaStatusCodeError):
    code: int = ...

class BadWouldBlock(UaStatusCodeError):
    code: int = ...

class BadSyntaxError(UaStatusCodeError):
    code: int = ...

class BadMaxConnectionsReached(UaStatusCodeError):
    code: int = ...
