"""
typing stub file
"""
from typing import Any, Union
from urllib.parse import ParseResult

import opcua
from opcua.client.ua_client import UaClient
from opcua.common import Node
from opcua.ua import uatypes

class Client:
    name: str
    description: str
    uaclient: UaClient

    server_url: ParseResult = ...
    def __init__(self, url: str, timeout: int = ...) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def get_root_node(self) -> opcua.Node: ...
    def get_objects_node(self) -> opcua.Node: ...
    def get_server_node(self) -> opcua.Node: ...
    def get_node(
        self, nodeid: Union[str, bytes, Node, uatypes.NodeId]
    ) -> opcua.Node: ...
    def get_namespace_index(self, uri: str) -> int: ...
