"""
typing stub file
"""

from enum import IntEnum

class AttributeIds(IntEnum):
    NodeId: int = ...
    NodeClass: int = ...
    BrowseName: int = ...
    DisplayName: int = ...
    Description: int = ...
    WriteMask: int = ...
    UserWriteMask: int = ...
    IsAbstract: int = ...
    Symmetric: int = ...
    InverseName: int = ...
    ContainsNoLoops: int = ...
    EventNotifier: int = ...
    Value: int = ...
    DataType: int = ...
    ValueRank: int = ...
    ArrayDimensions: int = ...
    AccessLevel: int = ...
    UserAccessLevel: int = ...
    MinimumSamplingInterval: int = ...
    Historizing: int = ...
    Executable: int = ...
    UserExecutable: int = ...
    DataTypeDefinition: int = ...
    RolePermissions: int = ...
    UserRolePermissions: int = ...
    AccessRestrictions: int = ...
    AccessLevelEx: int = ...
